version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - .env
