[tool.poetry]
name = "mongo-parent-document-retrieval"
version = "0.0.1"
description = "RAG using MongoDB and OpenAI"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"
pymongo = "^4.6.0"
pypdf = "^3.17.0"
tiktoken = "^0.5.1"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "mongo_parent_document_retrieval"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["MongoDB", "OpenAI"]
tags = ["vectordb"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
